### ISSUE TITLE
lib folder missing when installed from npm 

### ISSUE THREAD

**Issue by atuttle** [Splact/react-occamy-text#1]
This lib looks awesome, but I can't get it running.

```shellsession
$ npm install --save react-occamy-text
$ cat node_modules/react-occamy-text/package.json | grep main
"main": "lib/OccamyText.js",
$ cat node_modules/react-occamy-text/lib/OccamyText.js
cat: node_modules/react-occamy-text/lib/OccamyText.js: No such file or directory
```

Package.json indicates that it should use `lib/OccamyText.js` as the entrypoint into the module, but that file doesn't exist.

I tried building it locally, but that failed:

```shellsession
$ cd node_modules/react-occamy-text && npm install && npm run build
> react-occamy-text@1.0.3 build /Users/atcodes/.../node_modules/react-occamy-text
> gulp clean && NODE_ENV=production gulp build

/Users/atcodes/.../node_modules/react-occamy-text/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/atcodes/.../node_modules/react-occamy-text/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/Users/atcodes/.../node_modules/react-occamy-text/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/atcodes/.../node_modules/react-occamy-text/node_modules/react-component-gulp-tasks/tasks/release.js:1:73)
```

Node & NPM versions:

```shellsession
$ node -v && npm -v
v8.11.3
6.4.0
```

**Comment by Splact** [comment]
Thanks for rising this issue! I was very busy this month or so. I'll give a look during next days :)

**Comment by Splact** [comment]
I solved in a less rapid and drastic way 😅. Changed completely all the build tool moving to [Create React Library](https://github.com/transitive-bullshit/create-react-library) #2 .
